# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
