# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 08:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='votingtopic',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
